# Generated by Django 3.0.7 on 2020-06-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200609_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[(2, 'Bridal Makeup'), (3, 'Facial'), (4, 'Body Massage'), (5, 'Manicure')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined')], default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='Bookstatus',
        ),
    ]
