# Generated by Django 3.0.7 on 2020-06-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200613_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Bridal Makeup', 'Bridal Makeup'), ('Facial', 'Facial'), ('Body Massage', 'Body Massage'), ('Manicure', 'Manicure'), ('Massage', 'Massage')], max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
